name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/KoteskiOlmesLB-426

    - name: Build solution
      run: dotnet build --no-restore --configuration Release
      working-directory: src/KoteskiOlmesLB-426

    - name: Run tests
      run: dotnet test --configuration Debug --verbosity normal
      working-directory: src/KoteskiOlmesLB-426
